// <auto-generated />
using System;
using LetWeCook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LetWeCook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LetWeCookDbContext))]
    [Migration("20250615172912_AggregateUserRecipeInteractionsMigration")]
    partial class AggregateUserRecipeInteractionsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LetWeCook.Application.DTOs.UserInteractions.AggregatedInteractionDto", b =>
                {
                    b.Property<double?>("CommentLength")
                        .HasColumnType("float");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<double?>("DonatedAmount")
                        .HasColumnType("float");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double?>("Calories")
                        .HasColumnType("float")
                        .HasColumnName("calories");

                    b.Property<double?>("Carbohydrates")
                        .HasColumnType("float")
                        .HasColumnName("carbohydrates");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CoverImageUrlId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cover_image_url_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<double?>("ExpirationDays")
                        .HasColumnType("float")
                        .HasColumnName("expiration_days");

                    b.Property<double?>("Fat")
                        .HasColumnType("float")
                        .HasColumnName("fat");

                    b.Property<double?>("Fiber")
                        .HasColumnType("float")
                        .HasColumnName("fiber");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("bit")
                        .HasColumnName("is_gluten_free");

                    b.Property<bool>("IsPescatarian")
                        .HasColumnType("bit")
                        .HasColumnName("is_pescatarian");

                    b.Property<bool>("IsPreview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preview");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit")
                        .HasColumnName("is_vegan");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit")
                        .HasColumnName("is_vegetarian");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<double?>("Protein")
                        .HasColumnType("float")
                        .HasColumnName("protein");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float")
                        .HasColumnName("sodium");

                    b.Property<double?>("Sugar")
                        .HasColumnType("float")
                        .HasColumnName("sugar");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CoverImageUrlId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float")
                        .HasColumnName("average_rating");

                    b.Property<int>("CookTime")
                        .HasColumnType("int")
                        .HasColumnName("cook_time");

                    b.Property<Guid>("CoverMediaUrlId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cover_media_url_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("difficulty_level");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit")
                        .HasColumnName("is_preview");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("is_visible");

                    b.Property<string>("MealCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meal_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PrepareTime")
                        .HasColumnType("int")
                        .HasColumnName("prepare_time");

                    b.Property<int>("Servings")
                        .HasColumnType("int")
                        .HasColumnName("servings");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int")
                        .HasColumnName("total_ratings");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int")
                        .HasColumnName("total_views");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoverMediaUrlId")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.RecipeCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RecipeCount")
                        .HasColumnType("int")
                        .HasColumnName("recipe_count");

                    b.Property<Guid>("created_by_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_id");

                    b.HasKey("Id");

                    b.HasIndex("created_by_id");

                    b.ToTable("recipe_collections", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.SiteUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("date_joined")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_removed");

                    b.HasKey("Id");

                    b.ToTable("site_users", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.Detail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("details", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.DietaryPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("emoji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dietary_preferences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#808080",
                            Description = "No specific dietary preference",
                            Emoji = "❌",
                            Name = "None"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Color = "#4CAF50",
                            Description = "Excludes meat, includes dairy and eggs",
                            Emoji = "🥦",
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Color = "#8BC34A",
                            Description = "Excludes all animal products",
                            Emoji = "🌱",
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Color = "#FF9800",
                            Description = "Excludes gluten-containing grains",
                            Emoji = "🚫🌾",
                            Name = "GlutenFree"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Color = "#03A9F4",
                            Description = "Excludes meat but allows fish",
                            Emoji = "🐟",
                            Name = "Pescatarian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Color = "#FFEB3B",
                            Description = "Focuses on low-calorie meals",
                            Emoji = "🔥",
                            Name = "LowCalorie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Color = "#FF5722",
                            Description = "Emphasizes protein-rich foods",
                            Emoji = "💪",
                            Name = "HighProtein"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Color = "#9C27B0",
                            Description = "Limits carbohydrate intake (Keto-friendly)",
                            Emoji = "🥩",
                            Name = "LowCarb"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Color = "#2196F3",
                            Description = "Focuses on reducing fat intake",
                            Emoji = "🥗",
                            Name = "LowFat"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Color = "#E91E63",
                            Description = "Reduces added sugar consumption",
                            Emoji = "🚫🍭",
                            Name = "LowSugar"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Color = "#673AB7",
                            Description = "Emphasizes fiber-rich foods",
                            Emoji = "🌾",
                            Name = "HighFiber"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Color = "#00BCD4",
                            Description = "Focuses on reducing salt intake",
                            Emoji = "🧂🚫",
                            Name = "LowSodium"
                        });
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovalUrl")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("approval_url");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DonateMessage")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("donate_message");

                    b.Property<Guid>("DonatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("donator_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DonatorId");

                    b.HasIndex("RecipeId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.IngredientCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ingredient_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "All types of red and white meat",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Chicken, turkey, duck, and other birds",
                            Name = "Poultry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Fish, shellfish, and other seafood",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "All types of eggs used in cooking",
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "Milk, cheese, yogurt, and butter",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "Plant-based dairy substitutes like almond milk and soy milk",
                            Name = "Dairy alternatives"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "Fresh, frozen, and canned vegetables",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Fresh, dried, and preserved fruits",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Description = "Rice, wheat, oats, and other grains",
                            Name = "Grains"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Description = "Beans, lentils, chickpeas, and peas",
                            Name = "Legumes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Description = "Fresh and dried herbs like basil and parsley",
                            Name = "Herbs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Description = "All types of spices such as cinnamon and cumin",
                            Name = "Spices"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Description = "Cooking oils such as olive oil and vegetable oil",
                            Name = "Oils"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Description = "Sugar, honey, and artificial sweeteners",
                            Name = "Sweeteners"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Description = "Non-alcoholic and alcoholic drinks",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Sauces, dressings, and seasonings",
                            Name = "Condiments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Pickled and fermented ingredients like kimchi and miso",
                            Name = "Fermented foods"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Almonds, cashews, walnuts, and other tree nuts",
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Description = "Chia seeds, flaxseeds, sunflower seeds, and others",
                            Name = "Seeds"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Description = "Flour, yeast, baking powder, and cocoa powder",
                            Name = "Baking essentials"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Description = "Vegetable, chicken, and beef broths or stocks",
                            Name = "Broths and stocks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Description = "Fallback category for unspecified ingredients",
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.IngredientDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("DetailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("detail_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("DetailId")
                        .IsUnique();

                    b.HasIndex("IngredientId");

                    b.ToTable("ingredient_details", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.MediaUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("MediaType")
                        .HasColumnType("int")
                        .HasColumnName("media_type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("media_urls", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeCollectionItem", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("added_at");

                    b.HasKey("RecipeId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("recipe_collection_items", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("DetailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("detail_id");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("DetailId")
                        .IsUnique();

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_details", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ingredient_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeRating", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RecipeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("recipe_ratings", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("recipe_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Italian"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Indian"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Thai"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Korean"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "American"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Mediterranean"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Middle Eastern"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Greek"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-123456789012"),
                            Name = "Brazilian"
                        },
                        new
                        {
                            Id = new Guid("23456789-2345-2345-2345-234567890123"),
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = new Guid("34567890-3456-3456-3456-345678901234"),
                            Name = "African"
                        },
                        new
                        {
                            Id = new Guid("45678901-4567-4567-4567-456789012345"),
                            Name = "German"
                        });
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.SuggestionFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("LikeOrDislike")
                        .HasColumnType("bit")
                        .HasColumnName("like_or_dislike");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("suggestion_feedbacks", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.UserInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double>("EventValue")
                        .HasColumnType("float")
                        .HasColumnName("event_value");

                    b.Property<DateTime>("InteractionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("interaction_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("interaction_type");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_interactions", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("facebook_url");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("instagram_url");

                    b.Property<string>("PayPalEmail")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paypal_email");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_picture_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.UserRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by_user_name");

                    b.Property<Guid>("NewReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("new_reference_id");

                    b.Property<Guid?>("OldReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("old_reference_id");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(1500)")
                        .HasColumnName("response_message");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("user_requests", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SiteUserId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.Models.DetailMediaUrl", b =>
                {
                    b.Property<Guid>("DetailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("detail_id");

                    b.Property<Guid>("MediaUrlId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("media_url_id");

                    b.HasKey("DetailId", "MediaUrlId");

                    b.HasIndex("MediaUrlId")
                        .IsUnique();

                    b.ToTable("detail_media_urls", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.Models.RecipeTagging", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("RecipeTagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_tag_id");

                    b.HasKey("RecipeId", "RecipeTagId");

                    b.HasIndex("RecipeTagId");

                    b.ToTable("recipe_tags_recipes", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.Models.UserDietaryPreference", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_profile_id");

                    b.Property<Guid>("DietaryPreferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dietary_preference_id");

                    b.HasKey("UserProfileId", "DietaryPreferenceId");

                    b.HasIndex("DietaryPreferenceId");

                    b.ToTable("user_dietary_preferences", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.Ingredient", b =>
                {
                    b.HasOne("LetWeCook.Domain.Entities.IngredientCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Entities.MediaUrl", "CoverImageUrl")
                        .WithOne()
                        .HasForeignKey("LetWeCook.Domain.Aggregates.Ingredient", "CoverImageUrlId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CoverImageUrl");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.Recipe", b =>
                {
                    b.HasOne("LetWeCook.Domain.Entities.MediaUrl", "CoverMediaUrl")
                        .WithOne()
                        .HasForeignKey("LetWeCook.Domain.Aggregates.Recipe", "CoverMediaUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverMediaUrl");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.RecipeCollection", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("created_by_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.Donation", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "Author")
                        .WithMany("DonationsReceived")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "Donator")
                        .WithMany("DonationsMade")
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", "Recipe")
                        .WithMany("Donations")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Donator");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.IngredientDetail", b =>
                {
                    b.HasOne("LetWeCook.Domain.Entities.Detail", "Detail")
                        .WithOne()
                        .HasForeignKey("LetWeCook.Domain.Entities.IngredientDetail", "DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.Ingredient", null)
                        .WithMany("IngredientDetails")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeCollectionItem", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.RecipeCollection", "Collection")
                        .WithMany("Recipes")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeDetail", b =>
                {
                    b.HasOne("LetWeCook.Domain.Entities.Detail", "Detail")
                        .WithOne()
                        .HasForeignKey("LetWeCook.Domain.Entities.RecipeDetail", "DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", null)
                        .WithMany("RecipeDetails")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.RecipeRating", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.SuggestionFeedback", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", null)
                        .WithOne("Profile")
                        .HasForeignKey("LetWeCook.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("LetWeCook.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("district");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("house_number");

                            b1.Property<string>("ProvinceOrCity")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("province_or_city");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("street");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ward");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("LetWeCook.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("LetWeCook.Domain.Entities.UserRequest", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.ApplicationUser", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.SiteUser", "SiteUser")
                        .WithOne()
                        .HasForeignKey("LetWeCook.Infrastructure.Persistence.ApplicationUser", "SiteUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteUser");
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.Models.DetailMediaUrl", b =>
                {
                    b.HasOne("LetWeCook.Domain.Entities.Detail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Entities.MediaUrl", "MediaUrl")
                        .WithMany()
                        .HasForeignKey("MediaUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("MediaUrl");
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.Models.RecipeTagging", b =>
                {
                    b.HasOne("LetWeCook.Domain.Aggregates.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Entities.RecipeTag", "RecipeTag")
                        .WithMany()
                        .HasForeignKey("RecipeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeTag");
                });

            modelBuilder.Entity("LetWeCook.Infrastructure.Persistence.Models.UserDietaryPreference", b =>
                {
                    b.HasOne("LetWeCook.Domain.Entities.DietaryPreference", "DietaryPreference")
                        .WithMany()
                        .HasForeignKey("DietaryPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryPreference");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LetWeCook.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LetWeCook.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetWeCook.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LetWeCook.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.Ingredient", b =>
                {
                    b.Navigation("IngredientDetails");
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.Recipe", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Ratings");

                    b.Navigation("RecipeDetails");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.RecipeCollection", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("LetWeCook.Domain.Aggregates.SiteUser", b =>
                {
                    b.Navigation("DonationsMade");

                    b.Navigation("DonationsReceived");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
