apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-cook-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-cook-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-cook
  template:
    metadata:
      labels:
        app: mssql-cook
    spec:
      initContainers:
        - name: volume-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
            - name: mssqlauthdb
              mountPath: /var/opt/mssql
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-cook-secret
                  key: SA_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqlauthdb
      volumes:
        - name: mssqlauthdb
          persistentVolumeClaim:
            claimName: mssql-cook-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-cook-clusterip-srv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mssql-cook
  ports:
    - name: mssql
      protocol: TCP
      port: 1433
      targetPort: 1433
