namespace LetWeCook.Domain.Exceptions;

public enum ErrorCode
{
    UNKNOWN_ERROR = 0,
    USER_ALREADY_EXISTS = 1,
    USER_NOT_FOUND = 2,
    RECIPE_COLLECTION_USER_NOT_FOUND = 3,
    RECIPE_COLLECTION_NOT_FOUND = 4,
    RECIPE_COLLECTION_NOT_BELONG_TO_USER = 5,
    RECIPE_COLLECTION_RECIPE_NOT_FOUND = 6,
    RECIPE_COLLECTION_NAME_EMPTY = 7,
    RECIPE_COLLECTION_NAME_TOO_LONG = 8,
    RECIPE_COLLECTION_NAME_TOO_SHORT = 9,
    RECIPE_COLLECTION_NAME_EXISTS = 10,
    UPDATE_PROFILE_USER_NOT_FOUND = 11,
    UPDATE_PROFILE_INVALID_GENDER = 12,
    DONATION_NOT_FOUND = 13,
    DONATION_RECIPE_NOT_FOUND = 14,
    DONATION_DONATOR_NOT_FOUND = 15,
    DONATION_AUTHOR_NOT_FOUND = 16,
    DONATION_AUTHOR_PROFILE_NOT_FOUND = 17,
    DONATION_AUTHOR_PAYPAL_NOT_FOUND = 18,
    INGREDIENT_NOT_FOUND = 19,
    INGREDIENT_NOT_OWNED_BY_USER = 20,
    INGREDIENT_USER_NOT_FOUND = 21,
    INGREDIENT_NAME_EXISTS = 22,
    INGREDIENT_SITE_USER_ID_IS_NULL = 23,
    RECIPE_NOT_FOUND = 24,

}